# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

image: atlassian/default-image:3

pipelines:
  default:
    - parallel:
      - step:
          image: maven:3.3.9
          name: 'demo file'
          script:
            - javac f1/f2/f3/src/Destination.java 
            - cd f1/f2/f3/src/
            - java Destination.java   
